// Generated by using rustinr::rustrize() -> do not edit by hand

#include <Rinternals.h>
#include <R.h>

extern SEXP rustr_do_verb_multi_part_r(SEXP verb, SEXP headers, SEXP url, SEXP query, SEXP body, SEXP response_type);
SEXP teRcenHttp_do_verb_multi_part_r(SEXP verb, SEXP headers, SEXP url, SEXP query, SEXP body, SEXP response_type){ return(rustr_do_verb_multi_part_r(verb,headers,url,query,body,response_type));}
extern SEXP rustr_do_verb_r(SEXP verb, SEXP headers, SEXP url, SEXP query, SEXP body, SEXP content_type, SEXP response_type);
SEXP teRcenHttp_do_verb_r(SEXP verb, SEXP headers, SEXP url, SEXP query, SEXP body, SEXP content_type, SEXP response_type){ return(rustr_do_verb_r(verb,headers,url,query,body,content_type,response_type));}
extern SEXP rustr_do_verb(SEXP verb, SEXP headers, SEXP url, SEXP query, SEXP body, SEXP response_type);
SEXP teRcenHttp_do_verb(SEXP verb, SEXP headers, SEXP url, SEXP query, SEXP body, SEXP response_type){ return(rustr_do_verb(verb,headers,url,query,body,response_type));}
