# Generated by using rustinr::rustrize() -> do not edit by hand


do_verb_multi_part_r = function(verb,headers,url,query,body,response_type){ .Call('teRcenHttp_do_verb_multi_part_r',PACKAGE = 'teRcenHttp', verb,headers,url,query,body,response_type)}

do_verb_r = function(verb,headers,url,query,body,content_type,response_type){ .Call('teRcenHttp_do_verb_r',PACKAGE = 'teRcenHttp', verb,headers,url,query,body,content_type,response_type)}

do_verb = function(verb,headers,url,query,body,response_type){ .Call('teRcenHttp_do_verb',PACKAGE = 'teRcenHttp', verb,headers,url,query,body,response_type)}
