# Generated by using rustinr::rustrize() -> do not edit by hand


to_tson = function(object){ .Call('teRcenHttp_to_tson',PACKAGE = 'teRcenHttp', object)}

from_tson = function(rbytes){ .Call('teRcenHttp_from_tson',PACKAGE = 'teRcenHttp', rbytes)}

to_json = function(object){ .Call('teRcenHttp_to_json',PACKAGE = 'teRcenHttp', object)}

from_json = function(data){ .Call('teRcenHttp_from_json',PACKAGE = 'teRcenHttp', data)}

do_verb_multi_part_r = function(verb,headers,url,query,body,response_type){ .Call('teRcenHttp_do_verb_multi_part_r',PACKAGE = 'teRcenHttp', verb,headers,url,query,body,response_type)}

do_verb_r = function(verb,headers,url,query,body,content_type,response_type){ .Call('teRcenHttp_do_verb_r',PACKAGE = 'teRcenHttp', verb,headers,url,query,body,content_type,response_type)}

do_verb = function(verb,headers,url,query,body,response_type){ .Call('teRcenHttp_do_verb',PACKAGE = 'teRcenHttp', verb,headers,url,query,body,response_type)}
